# Generated by Django 4.0.5 on 2022-06-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleclibrary', '0002_remove_authors_birth_date_alter_books_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['title'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.RenameField(
            model_name='books',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books',
            name='year',
        ),
        migrations.AddField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='authors', to='eleclibrary.books'),
        ),
    ]
